[package]
name = "rs-es"
version = "0.8.0"
authors = ["Ben Ashford"]
license = "Apache-2.0"
repository = "https://github.com/benashford/rs-es"
documentation = "http://benashford.github.io/rs-es/rs_es/index.html"
description = "Client for the ElasticSearch REST API"
readme = "README.md"
keywords = ["elasticsearch", "elastic"]
exclude = ["devbox/**/*", "docker-dev.yml"]

[lib]
name = "rs_es"

[features]
default = ["ssl"]
ssl = ["hyper-openssl"]

[dependencies]
hyper = "^0.10"
hyper-openssl = { version = "^0.2", optional = true }
log = "^0.3"
maplit = "^0.1"
serde = "^0.9"
serde_json = "^0.9"
serde_derive = "^0.9"
url = "^1.2"

[dev-dependencies]
env_logger = "^0.4"
regex = "^0.2"
